namespace HondaEcu.Core.Tests;

public sealed class P28CompactModelTests
{
    // Hand-calculated integer boundary cases, not an OEM-derived byte corpus or output
    // generated by the implementation under test. The private instruction-oriented
    // reference comparison is a separate, explicitly reported validation operation.
    [Theory]
    [InlineData(0, 255, true, P28CompactBranch.LowRaw255)]
    [InlineData(186, 255, true, P28CompactBranch.LowRaw255)]
    [InlineData(187, 254, true, P28CompactBranch.LowRaw254)]
    [InlineData(233, 254, true, P28CompactBranch.LowRaw254)]
    [InlineData(234, 254, true, P28CompactBranch.UpperClamp)]
    [InlineData(235, 254, true, P28CompactBranch.UpperClamp)]
    [InlineData(236, 254, true, P28CompactBranch.UpperClamp)]
    [InlineData(237, 254, true, P28CompactBranch.Normal)]
    [InlineData(467, 192, false, P28CompactBranch.Normal)]
    [InlineData(468, 192, false, P28CompactBranch.Normal)]
    [InlineData(469, 191, true, P28CompactBranch.Normal)]
    [InlineData(936, 128, false, P28CompactBranch.Normal)]
    [InlineData(937, 128, false, P28CompactBranch.Normal)]
    [InlineData(938, 127, true, P28CompactBranch.Normal)]
    [InlineData(1874, 64, false, P28CompactBranch.Normal)]
    [InlineData(1875, 64, false, P28CompactBranch.Normal)]
    [InlineData(1876, 63, true, P28CompactBranch.Normal)]
    [InlineData(3692, 1, false, P28CompactBranch.Normal)]
    [InlineData(3693, 1, false, P28CompactBranch.ZeroClamp)]
    [InlineData(3749, 1, false, P28CompactBranch.ZeroClamp)]
    public void HypothesisIntegerBoundariesDoNotDependOnHighRawContext(
        ushort raw, byte code, bool extraBit, P28CompactBranch branch)
    {
        var expected = new P28CompactHypothesisResult(code, extraBit, branch);
        Assert.Equal(expected, P28CompactModel.EvaluateHypothesis(raw, false));
        Assert.Equal(expected, P28CompactModel.EvaluateHypothesis(raw, true));
    }

    [Theory]
    [InlineData(3750)]
    [InlineData(65535)]
    public void HighRawRequiresExplicitEntryContext(ushort raw)
    {
        Assert.Equal(new P28CompactResult(1, false, P28CompactBranch.HighRaw, true), P28CompactModel.Evaluate(raw, false));
        Assert.Equal(new P28CompactResult(0, false, P28CompactBranch.HighRaw, true), P28CompactModel.Evaluate(raw, true));
    }

    [Fact]
    public void HypothesisZeroCodeIsUnreachableWithClearContextWhileEstablishedReachabilityIsUnknown()
    {
        var domain = P28CompactModel.GetDomain(0, false);
        Assert.False(domain.HypothesisReachable);
        Assert.Null(domain.Reachable);
        Assert.Empty(domain.ExactInputs);
        Assert.Equal(65536, Count(domain.HypothesisPredicateInputs));
        Assert.Equal(62020, Count(domain.PredicateInputs));

        var set = P28CompactModel.GetDomain(0, true);
        Assert.True(set.Reachable);
        Assert.Equal(new[] { new P28RawRange(3750, 65535, P28CompactBranch.HighRaw) }, set.ExactInputs);
        Assert.Equal(234, Count(set.PredicateInputs));
        Assert.Equal(3750, Count(set.HypothesisPredicateInputs));
    }

    [Fact]
    public void HighestCodeHasExactInputsButAnEmptyStrictPredicate()
    {
        foreach (var context in new[] { false, true })
        {
            var domain = P28CompactModel.GetDomain(255, context);
            Assert.Equal(new[] { new P28RawRange(0, 186, P28CompactBranch.LowRaw255) }, domain.ExactInputs);
            Assert.Empty(domain.PredicateInputs);
        }
    }

    [Fact]
    public void DomainKeepsBranchAndSaturationBoundaries()
    {
        var domain = P28CompactModel.GetDomain(254, false);
        Assert.Equal(new[]
        {
            new P28RawRange(187, 233, P28CompactBranch.LowRaw254),
            new P28RawRange(234, 236, P28CompactBranch.UpperClamp),
            new P28RawRange(237, 238, P28CompactBranch.Normal),
        }, domain.HypothesisExactInputs);
        Assert.Equal(new[] { new P28RawRange(187, 233, P28CompactBranch.LowRaw254) }, domain.ExactInputs);
        Assert.Equal(new[] { new P28RawRange(0, 186, P28CompactBranch.LowRaw255) }, domain.PredicateInputs);
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void HypothesisPreimagesPartitionDomainWhileEstablishedRangesExcludeUnresolvedPaths(bool context)
    {
        var domains = P28CompactModel.GetAllDomains(context);
        Assert.Equal(256, domains.Count);
        var covered = new int[65536];
        foreach (var domain in domains)
        {
            Assert.Equal(domain.HypothesisExactInputs.Count != 0, domain.HypothesisReachable);
            Assert.Equal(domain.ExactInputs.Count != 0 ? true : (bool?)null, domain.Reachable);
            Assert.Equal(context, domain.Data0217Bit4);
            Assert.Equal(new[] { new P28RawRange(234, 3749, P28CompactBranch.Unresolved) }, domain.UnresolvedInputs);
            Assert.All(domain.ExactInputs.Concat(domain.PredicateInputs),
                range => Assert.True(range.EndInclusive < 234 || range.StartInclusive >= 3750));
            foreach (var range in domain.HypothesisExactInputs)
            {
                Assert.InRange(range.StartInclusive, 0, 65535);
                Assert.InRange(range.EndInclusive, range.StartInclusive, 65535);
                for (var raw = range.StartInclusive; raw <= range.EndInclusive; raw++)
                {
                    covered[raw]++;
                    Assert.Equal(domain.Code, P28CompactModel.EvaluateHypothesis((ushort)raw, context).Code);
                }
            }

            // This checks range construction consistency, not independent arithmetic evidence.
            foreach (var range in domain.HypothesisPredicateInputs)
            {
                Assert.True(P28CompactModel.EvaluateHypothesis((ushort)range.StartInclusive, context).Code > domain.Code);
                Assert.True(P28CompactModel.EvaluateHypothesis((ushort)range.EndInclusive, context).Code > domain.Code);
            }
        }

        Assert.All(covered, count => Assert.Equal(1, count));

        // Reuse the domains above. This is full-domain range-construction consistency,
        // not independent evidence that the hypothesis matches the original instructions.
        byte[] selectedCodes = { 0, 1, 63, 64, 127, 128, 192, 254, 255 };
        var selectedMembership = selectedCodes.Select(code => new
        {
            Code = code,
            Hypothesis = RangeMembership(domains[code].HypothesisPredicateInputs),
            Established = RangeMembership(domains[code].PredicateInputs),
        }).ToArray();

        for (var raw = 0; raw <= ushort.MaxValue; raw++)
        {
            var hypothesis = P28CompactModel.EvaluateHypothesis((ushort)raw, context);
            var established = P28CompactModel.Evaluate((ushort)raw, context);
            foreach (var membership in selectedMembership)
            {
                Assert.Equal(hypothesis.Code > membership.Code, membership.Hypothesis[raw]);
                Assert.Equal(
                    established.Resolved && established.Code.HasValue && established.Code.Value > membership.Code,
                    membership.Established[raw]);
                if (!established.Resolved)
                {
                    Assert.False(membership.Established[raw]);
                }
            }
        }
    }

    [Fact]
    public void UnresolvedInstructionPathNeverReturnsAClaimedValue()
    {
        foreach (var context in new[] { false, true })
        {
            var resolved = 0;
            var unresolved = 0;
            for (var raw = 0; raw <= ushort.MaxValue; raw++)
            {
                var result = P28CompactModel.Evaluate((ushort)raw, context);
                if (raw is >= 234 and < 3750)
                {
                    Assert.False(result.Resolved);
                    Assert.Null(result.Code);
                    Assert.Null(result.ExtraBit);
                    Assert.Equal(P28CompactBranch.Unresolved, result.Branch);
                    unresolved++;
                }
                else
                {
                    Assert.True(result.Resolved);
                    Assert.NotNull(result.Code);
                    Assert.NotNull(result.ExtraBit);
                    resolved++;
                }
            }

            Assert.Equal(62020, resolved);
            Assert.Equal(3516, unresolved);
        }
    }

    private static int Count(IReadOnlyList<P28RawRange> ranges) =>
        ranges.Sum(range => range.EndInclusive - range.StartInclusive + 1);

    private static bool[] RangeMembership(IReadOnlyList<P28RawRange> ranges)
    {
        var membership = new bool[65536];
        foreach (var range in ranges)
        {
            Assert.InRange(range.StartInclusive, 0, ushort.MaxValue);
            Assert.InRange(range.EndInclusive, range.StartInclusive, ushort.MaxValue);
            for (var raw = range.StartInclusive; raw <= range.EndInclusive; raw++)
            {
                Assert.False(membership[raw]);
                membership[raw] = true;
            }
        }

        return membership;
    }
}
