namespace HondaEcu.Core.Tests;

internal sealed class SyntheticFixture : IDisposable
{
    public SyntheticFixture()
    {
        DirectoryPath = Path.Combine(Path.GetTempPath(), "hondaecu-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(DirectoryPath);
    }

    public string DirectoryPath { get; }

    public string PathFor(string name) => Path.Combine(DirectoryPath, name);

    public string WriteRom(string name, byte[] bytes)
    {
        var path = PathFor(name);
        File.WriteAllBytes(path, bytes);
        return path;
    }

    public void Dispose()
    {
        if (Directory.Exists(DirectoryPath))
        {
            Directory.Delete(DirectoryPath, recursive: true);
        }
    }

    public static byte[] Bytes(int size = 32768)
    {
        var bytes = new byte[size];
        for (var index = 0; index < bytes.Length; index++)
        {
            bytes[index] = (byte)(((index * 37) + 11) & 0xFF);
        }

        return bytes;
    }

    public static RomProfile Profile(int size = 32768, int checksumOffset = 30000)
    {
        var parameters = new[]
        {
            Scalar("raw_u8", 100, 1, Endianness.NotApplicable, new(ParameterEncodingType.RawU8), 0, 255, 0, 255),
            Scalar("raw_s8", 101, 1, Endianness.NotApplicable, new(ParameterEncodingType.RawS8), -128, 127, -128, 127),
            Scalar("raw_u16_le", 102, 2, Endianness.Little, new(ParameterEncodingType.RawU16LittleEndian), 0, 65535, 0, 65535),
            Scalar("raw_u16_be", 104, 2, Endianness.Big, new(ParameterEncodingType.RawU16BigEndian), 0, 65535, 0, 65535),
            Scalar("linear_u8", 106, 1, Endianness.NotApplicable, new(ParameterEncodingType.LinearU8, scale: 2.5, offset: 100), 0, 255, 100, 737.5),
            Scalar("linear_u16", 108, 2, Endianness.Little, new(ParameterEncodingType.LinearU16, scale: 0.5, offset: -10), 0, 65535, -10, 32757.5),
            Scalar("inverse_u8", 110, 1, Endianness.NotApplicable, new(ParameterEncodingType.InverseU8, offset: 5, numerator: 60000, denominatorOffset: 1), 0, 255, 239.375, 60005),
            Scalar("lookup", 111, 1, Endianness.NotApplicable, new(ParameterEncodingType.LookupTable, values: new[] { 10d, 20d, 40d }), 0, 2, 10, 40),
            Scalar("rounded", 112, 1, Endianness.NotApplicable, new(ParameterEncodingType.LinearU8, scale: 2), 0, 255, 0, 510),
            Scalar("unverified", 113, 1, Endianness.NotApplicable, new(ParameterEncodingType.RawU8), 0, 255, 0, 255,
                ValidationLevel.PublicDocumentation),
            new ScalarParameterDefinition("read_only", "Read only", "Synthetic read-only value", 114, 1,
                Endianness.NotApplicable, new ParameterEncoding(ParameterEncodingType.RawU8), writable: false,
                validationLevel: ValidationLevel.CrossEditorConfirmed, revisionScope: "synthetic-v1"),
        };
        var tables = new[]
        {
            new TableParameterDefinition("table", "Table", "Synthetic two by two table", 200, 4, 2, 2, 1,
                Endianness.NotApplicable, new ParameterEncoding(ParameterEncodingType.RawU8), rawMinimum: 0, rawMaximum: 255,
                engineeringMinimum: 0, engineeringMaximum: 255, roundingPolicy: RoundingPolicy.Exact, writable: true,
                validationLevel: ValidationLevel.CrossEditorConfirmed, revisionScope: "synthetic-v1", status: ParameterStatus.Experimental),
        };
        return new RomProfile("synthetic-test-rom", "Synthetic test ROM", "Generated bytes only", size,
            "synthetic-v1", experimental: true, requiresExplicitConfirmation: true, parameters: parameters, tables: tables,
            checksum: new ChecksumDefinition("unknown", ChecksumStatus.Unknown, checksumOffset, 1,
                ValidationLevel.PublicDocumentation));
    }

    private static ScalarParameterDefinition Scalar(
        string id,
        int offset,
        int width,
        Endianness endianness,
        ParameterEncoding encoding,
        double rawMinimum,
        double rawMaximum,
        double engineeringMinimum,
        double engineeringMaximum,
        ValidationLevel validationLevel = ValidationLevel.CrossEditorConfirmed) =>
        new(id, id, $"Synthetic {id}", offset, width, endianness, encoding, "synthetic", rawMinimum, rawMaximum,
            engineeringMinimum, engineeringMaximum, RoundingPolicy.Nearest, writable: true, validationLevel,
            "synthetic-v1", status: ParameterStatus.Experimental);
}
