<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HondaEcu.Core\HondaEcu.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\definitions\**\*.json"
             Link="definitions\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>hondaecu</AssemblyName>
    <RootNamespace>HondaEcu.Cli</RootNamespace>
  </PropertyGroup>

</Project>
