//! Invented exact-form regressions, never OEM chain/reachability evidence.
use crate::{
    bus::Bus,
    common_result_consumer::admission,
    cpu::Cpu,
    decoder::decode,
    exec::{read_data_u16, step, write_data_u16},
    instruction_forms::FormAdmission,
};

#[test]
fn invented_positive_word_div_256_cases_cover_high_quotient_flags_dd_and_banks() {
    for dividend in [
        0u32, 1, 10, 65535, 65536, 0x12345678, 0xFFFF0000, 0xFFFFFFFF,
    ] {
        for divisor in [1u16, 2, 37, 65535] {
            for dd in [false, true] {
                for hc in [false, true] {
                    for lrb in [0x20u16, 0x43] {
                        let mut cpu = Cpu::new();
                        let mut bus = Bus::new(vec![0x90, 0x37], 0xA5);
                        cpu.lrb = lrb;
                        cpu.set_psw_u16(0xEF31);
                        cpu.dd = dd;
                        cpu.hc = hc;
                        cpu.a = dividend as u16;
                        let bank = cpu.bank_base();
                        write_data_u16(&mut cpu, &mut bus, bank, (dividend >> 16) as u16);
                        write_data_u16(&mut cpu, &mut bus, bank + 2, 0xBEEF);
                        write_data_u16(&mut cpu, &mut bus, bank + 4, divisor);
                        write_data_u16(&mut cpu, &mut bus, bank + 6, 0x7654);
                        let preserved = cpu.psw_u16() & !(Cpu::PSW_CF_BIT | Cpu::PSW_ZF_BIT);
                        bus.begin_write_journal();
                        let d = step(&mut cpu, &mut bus).unwrap();
                        let q = dividend / u32::from(divisor);
                        let rem = dividend % u32::from(divisor);
                        assert_eq!(d.mnemonic, "DIV");
                        assert_eq!(d.len, 2);
                        assert_eq!(cpu.pc, 2);
                        assert_eq!(read_data_u16(&cpu, &mut bus, bank), (q >> 16) as u16);
                        assert_eq!(cpu.a, q as u16);
                        assert_eq!(read_data_u16(&cpu, &mut bus, bank + 2), rem as u16);
                        assert_eq!(read_data_u16(&cpu, &mut bus, bank + 4), divisor);
                        assert_eq!(read_data_u16(&cpu, &mut bus, bank + 6), 0x7654);
                        assert!(!cpu.cf);
                        assert_eq!(cpu.zf, q == 0);
                        assert_eq!(
                            cpu.psw_u16() & !(Cpu::PSW_CF_BIT | Cpu::PSW_ZF_BIT),
                            preserved
                        );
                        assert_eq!(
                            bus.end_write_journal(),
                            vec![
                                [u32::from(bank), 16, q >> 16],
                                [u32::from(bank + 2), 16, rem]
                            ]
                        );
                    }
                }
            }
        }
    }
}
#[test]
fn invented_zero_div_only_asserts_defined_carry_not_undefined_numbers_or_zero_flag() {
    let mut cpu = Cpu::new();
    let mut bus = Bus::new(vec![0x90, 0x37], 0xA5);
    cpu.lrb = 0x20;
    cpu.a = 0xBEEF;
    cpu.set_psw_u16(0x3331);
    write_data_u16(&mut cpu, &mut bus, 0x104, 0);
    assert_eq!(step(&mut cpu, &mut bus).unwrap().mnemonic, "DIV");
    assert!(cpu.cf);
    // Deliberately no quotient/remainder/ZF assertion. Strict chain never calls this on zero.
}
#[test]
fn disputed_gt_is_not_admitted_in_any_of_four_flag_states() {
    for cf in [false, true] {
        for zf in [false, true] {
            let mut cpu = Cpu::new();
            cpu.cf = cf;
            cpu.zf = zf;
            let d = decode(cpu.dd, |i| [0xC8, 7].get(i).copied().unwrap_or(0)).unwrap();
            assert_eq!(d.mnemonic, "JGT rel8");
            assert_eq!(d.len, 2);
            assert_eq!(admission(&d), FormAdmission::Unsupported);
            // No executor branch observation can settle a primary evidence conflict.
        }
    }
}
#[test]
fn invented_cmp_generated_below_equal_above_flags_leave_gt_unadmitted() {
    for a in [10u16, 11, 12] {
        // Two distinct invented stores would distinguish branch results if admitted.
        let mut bus = Bus::new(
            vec![0xC6, 11, 0, 0xC8, 4, 0xD5, 0xE0, 0xCB, 2, 0xD5, 0xE1],
            0xA5,
        );
        let mut cpu = Cpu::new();
        cpu.dd = true;
        cpu.a = a;
        cpu.hc = true;
        step(&mut cpu, &mut bus).unwrap();
        assert_eq!(cpu.pc, 3);
        assert_eq!(cpu.a, a);
        assert_eq!(cpu.cf, a < 11);
        assert_eq!(cpu.zf, a == 11);
        assert!(cpu.hc);
        assert!(cpu.dd);
        let d = decode(cpu.dd, |i| bus.peek_code_u8(3 + i).unwrap()).unwrap();
        assert_eq!(admission(&d), FormAdmission::Unsupported);
        assert_eq!(read_data_u16(&cpu, &mut bus, 0xE0), 0xA5A5);
        // CF1/ZF1 cannot be generated by one ordinary unsigned CMP; direct test above covers it.
    }
}
